### ISSUE TITLE
Consider supporting string to HTML for browser

### ISSUE THREAD

**Issue by aidenybai** [lucialand/luciascript#1]
https://github.com/lucialand/luciascript/blob/main/src/index.ts#L16 

Currently seems to just construct a string, maybe for browser circumstances create a temp wrapper element to convert it into HTML. 

```js
const temp = document.createElement('div');
temp.innerHTML = final;
return temp.firstChild;
```

**Comment by shadowtime2000** [comment]
I am not as much of a fan of this idea because that would limit it's usability in Node or other server side JS environments. This could be done in packages that use Luciascript (e.g. `lucia-jsx`).
